# Generated by Django 5.1.7 on 2025-03-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('full_url', models.CharField(blank=True, max_length=500, null=True)),
                ('image_urls', models.TextField(blank=True, null=True)),
                ('avg_rating', models.CharField(blank=True, max_length=500, null=True)),
                ('price_per_night', models.CharField(blank=True, max_length=500, null=True)),
                ('total_price', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'scrapper',
                'managed': False,
            },
        ),
    ]
